/**
 * Injection tokens for NotificationKit providers
 */
export const NOTIFICATION_KIT_OPTIONS = Symbol("NOTIFICATION_KIT_OPTIONS");
export const NOTIFICATION_SERVICE = Symbol("NOTIFICATION_SERVICE");
export const NOTIFICATION_REPOSITORY = Symbol("NOTIFICATION_REPOSITORY");
export const NOTIFICATION_SENDERS = Symbol("NOTIFICATION_SENDERS");
export const NOTIFICATION_ID_GENERATOR = Symbol("NOTIFICATION_ID_GENERATOR");
export const NOTIFICATION_DATETIME_PROVIDER = Symbol("NOTIFICATION_DATETIME_PROVIDER");
export const NOTIFICATION_TEMPLATE_ENGINE = Symbol("NOTIFICATION_TEMPLATE_ENGINE");
export const NOTIFICATION_EVENT_EMITTER = Symbol("NOTIFICATION_EVENT_EMITTER");
